name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - 'server/**' #UPDATE
      - 'Dockerfile'
      - '.github/workflows/**'
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server/ # UPDATE
          push: true
          tags: ghcr.io/jonorl/wheres-bluey:latest # UPDATE
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: | # UPDATE
            docker compose -f ~/my-VPS/projects/docker-compose.yml pull wheres-bluey
            docker compose -f ~/my-VPS/projects/docker-compose.yml up -d wheres-bluey